server:
  port: 8080

spring:
  application:
    name: ${rootProject.name}
    version: ${version}
  h2:
    console:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
