server:
  port: 9999

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: dayco-uaa

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


