server:
  port: 8000

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTION
              - DELETE
      routes:
        - id: dayco
          uri: http://localhost:8080
          predicates:
            - Path=/api/posts/**,/api/dayco-websocket/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: dayco-uaa
          uri: http://localhost:9999
          predicates:
            - Path=/api/user/**,/api/auth/**,/api/oauth2/**,/api/manager/**,/api/profile/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env
