server:
  port: 8761

# https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html
zuul:
  ignoredServices: '*'
  prefix: /v1
  routes:
    hello:
      path: /hello/**
      stripPrefix: false

ribbon:
  eureka:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

hello:
  ribbon:
    listOfServers: http://localhost:8080

